var res = {
   Title_png:"res/title2.png",
   gameover_png: "res/gameover_scene.png",
   clear_png: "res/clear_scene.png",
   player_png: "res/box_idol.png",
   //player_jump_png: "res/player_jump.png",
   player_idol_png: "res/box_idol.png",
   player_death_png: "res/player_death.png",

   no1_png:"res/no1.png",
   no2_png:"res/no2.png",
   no3_png:"res/no3.png",
   TitleButton_png:"res/button1.png",
   RetryButton_png:"res/button2.png",
   SoundButton_png:"res/button3.png",
   SoundOffButton_png:"res/button4.png",
   HelpButton_png:"res/book.png",


   terrain_png: "res/terrain.png",
   background1_png: "res/background1.jpg",
   background2_png: "res/background2.jpg",
   background3_png: "res/background3.jpg",
   background4_png: "res/background4.jpg",
   background5_png: "res/background5.jpg",
   background6_png: "res/background6.jpg",

   help_png:"res/help.png",

   map11: "res/map11.tmx",
   map12: "res/map12.tmx",
   map13: "res/map13.tmx",
   map21: "res/map21.tmx",
   map22: "res/map22.tmx",
   map23: "res/map23.tmx",
   map31: "res/map31.tmx",
   map32: "res/map32.tmx",
   map33: "res/map33.tmx",
   map41: "res/map41.tmx",
   map42: "res/map42.tmx",
   map43: "res/map43.tmx",
   map51: "res/map51.tmx",
   map52: "res/map52.tmx",
   map53: "res/map53.tmx",
   map61: "res/map61.tmx",
   map62: "res/map62.tmx",
   map63: "res/map63.tmx",
   map71: "res/map71.tmx",
   map72: "res/map72.tmx",
   map73: "res/map73.tmx",


   object_tsx: "res/object.tsx",
   terrain_tsx: "res/terrain.tsx",
   object_png: "res/object.png",

   ok_se: "res/se/decision-14.mp3",
   spring_mp3: "res/se/spring.mp3",
   pickup_coin_mp3: "res/se/coin.mp3",
   blockbreak_mp3:"res/se/blockbreak.mp3",
   push_se:"res/se/kettei.mp3",
   bell_mp3:"res/se/tirin1.mp3",
   clockbell_mp3:"res/se/ClockBell(two).mp3",
   tictac_mp3: "res/se/tictac(highspeed).mp3",
   draw_mp3: "res/se/draw_bow.mp3",
   delete_mp3:"res/se/delete.wav",
   jump2_mp3: "res/se/jump03.mp3",
   decide_mp3: "res/se/decide.mp3",
   complete_mp3: "res/se/complete.mp3",
   damage_mp3: "res/se/damage.mp3",
   up_mp3: "res/se/up.mp3",
   page_mp3: "res/se/page.mp3",
   credit_in:"res/se/credit_in.mp3",
   credit_out:"res/se/credit_out.mp3",
   bgm1:"res/bgm/gauru.mp3",
   bgm2:"res/bgm/WildArms.mp3",
   bgm3:"res/bgm/Theory_of_Eternity.mp3",
   bgm4:"res/bgm/Scars_of_FAUNA(loop).mp3",
   bgm5:"res/bgm/yellow_head_joe.mp3",
   bgm6:"res/bgm/arusutoromeria-loop.mp3",
   bgm7:"res/bgm/SQ4-2.mp3",
   bgm8:"res/bgm/irisu.mp3",
   bgm9:"res/bgm/tokimekiStream.mp3",
   fanfare:"res/se/clear.mp3"
};

var g_resources = [];
for (var i in res) {
   g_resources.push(res[i]);
}
